"""
Runs the SHACL shapes in data/shapes/ against the built colleague graph.
Anything that fails (currently: an sdo:Organization with no resolvable
institutional identifier - see data/shapes/organization_quality.ttl) is
removed from the graph along with the specific employment/funding entry
that referenced it, and returned as a report so a human-readable summary
can be written for the colleague to act on in ORCID itself.
"""
from pathlib import Path

from pyshacl import validate
from rdflib import Graph, Namespace
from rdflib.namespace import RDF

SDO = Namespace("https://schema.org/")
SH = Namespace("http://www.w3.org/ns/shacl#")
INTERNAL = Namespace("urn:orcidgraph:internal:")

DEFAULT_REASON = "no institutional identifier (e.g. ROR) attached in ORCID for this organization."

REPO_ROOT = Path(__file__).resolve().parent.parent
SHAPES_DIR = REPO_ROOT / "data" / "shapes"


def load_shapes():
    shapes = Graph()
    for path in sorted(SHAPES_DIR.glob("*.ttl")):
        shapes.parse(path, format="turtle")
    return shapes


def failing_organizations(g):
    shapes = load_shapes()
    _, results_graph, _ = validate(g, shacl_graph=shapes, inference="none")
    return {
        results_graph.value(result, SH.focusNode)
        for result in results_graph.subjects(RDF.type, SH.ValidationResult)
    }


def _describe(g, person, activity_uri, org_name, kind):
    reason = g.value(activity_uri, INTERNAL.reportReason) or DEFAULT_REASON
    return {
        "person_name": str(g.value(person, SDO.name)) if person else "unknown colleague",
        "person_orcid": str(person) if person else None,
        "organization": str(org_name) if org_name else "unnamed organization",
        "kind": kind,
        "activity_url": str(activity_uri),
        "reason": str(reason),
    }


def apply_quality_gate(g):
    """Mutates g in place, removing anything that fails a shape. Returns a
    list of dicts describing what was dropped and why."""
    report = []

    for org in failing_organizations(g):
        org_name = g.value(org, SDO.name)

        for role in list(g.subjects(SDO.worksFor, org)):
            person = next(g.subjects(SDO.worksFor, role), None)
            report.append(_describe(g, person, role, org_name, "employment"))
            g.remove((person, SDO.worksFor, role))
            g.remove((role, None, None))

        for grant in list(g.subjects(SDO.funder, org)):
            person = g.value(grant, SDO.fundedItem)
            report.append(_describe(g, person, grant, org_name, "funding"))
            g.remove((grant, None, None))

        g.remove((org, None, None))

    return report


def write_report(report, path):
    if not report:
        Path(path).unlink(missing_ok=True)
        return

    by_person = {}
    for item in report:
        by_person.setdefault((item["person_name"], item["person_orcid"]), []).append(item)

    lines = [
        "# ORCID entries to fix",
        "",
        "Generated by scripts/build_colleague_graph.py. These entries were left",
        "out of data/colleagues.ttl - each line below says why, and links to the",
        "exact entry in ORCID to go edit. They'll be picked up automatically the",
        "next time the graph is rebuilt.",
        "",
    ]
    for (name, orcid), items in sorted(by_person.items()):
        lines.append(f"## {name} ({orcid})")
        lines.append("")
        for item in items:
            lines.append(f"- {item['kind']} at \"{item['organization']}\": {item['reason']}")
            lines.append(f"  {item['activity_url']}")
        lines.append("")

    Path(path).write_text("\n".join(lines))
