"""Runs the SHACL shapes in data/shapes/ against the built colleague graph.
Anything that fails (currently: an sdo:Organization with no resolvable
institutional identifier - see data/shapes/organization_quality.ttl) is
removed from the graph along with the specific employment/funding entry
that referenced it, and returned as a report so a human-readable summary
can be written for the colleague to act on in ORCID itself.
"""
from __future__ import annotations

import re
from pathlib import Path

from pyshacl import validate
from rdflib import Graph, Namespace
from rdflib.namespace import RDF

from .prefixes import INTERNAL, SDO

SH = Namespace("http://www.w3.org/ns/shacl#")

DEFAULT_REASON = "no institutional identifier (e.g. ROR) attached in ORCID for this organization."

REPO_ROOT = Path(__file__).resolve().parent.parent
SHAPES_DIR = REPO_ROOT / "data" / "shapes"


def load_shapes() -> Graph:
    shapes = Graph()
    for path in sorted(SHAPES_DIR.glob("*.ttl")):
        shapes.parse(path, format="turtle")
    return shapes


def failing_organizations(g: Graph):
    shapes = load_shapes()
    _, results_graph, _ = validate(g, shacl_graph=shapes, inference="none")
    return {
        results_graph.value(result, SH.focusNode)
        for result in results_graph.subjects(RDF.type, SH.ValidationResult)
    }


def _describe(g, person, activity_uri, org_name, kind):
    reason = g.value(activity_uri, INTERNAL.reportReason) or DEFAULT_REASON
    return {
        "person_name": str(g.value(person, SDO.name)) if person else "unknown colleague",
        "person_family_name": str(g.value(person, SDO.familyName)) if person else None,
        "person_orcid": str(person) if person else None,
        "organization": str(org_name) if org_name else "unnamed organization",
        "kind": kind,
        "activity_url": str(activity_uri),
        "reason": str(reason),
    }


def apply_quality_gate(g: Graph) -> list[dict]:
    """Mutates g in place, removing anything that fails a shape. Returns a
    list of dicts describing what was dropped and why."""
    report = []

    for org in failing_organizations(g):
        org_name = g.value(org, SDO.name)

        for role in list(g.subjects(SDO.worksFor, org)):
            person = next(g.subjects(SDO.worksFor, role), None)
            report.append(_describe(g, person, role, org_name, "employment"))
            g.remove((person, SDO.worksFor, role))
            g.remove((role, None, None))

        for grant in list(g.subjects(SDO.funder, org)):
            person = g.value(grant, SDO.fundedItem)
            report.append(_describe(g, person, grant, org_name, "funding"))
            g.remove((grant, None, None))

        g.remove((org, None, None))

    return report


def _group_by_person(report):
    by_person = {}
    for item in report:
        by_person.setdefault((item["person_name"], item["person_orcid"]), []).append(item)
    return by_person


def _slugify(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def _issue_lines(items):
    lines = []
    for item in items:
        lines.append(f"- {item['kind']} at \"{item['organization']}\": {item['reason']}")
        lines.append(f"  {item['activity_url']}")
    return lines


def write_report(report, path):
    if not report:
        Path(path).unlink(missing_ok=True)
        return

    by_person = _group_by_person(report)

    lines = [
        "# ORCID entries to fix",
        "",
        "Generated by `python -m orcid_etl.cli`. These entries were left out of",
        "the built graph - each line below says why, and links to the exact",
        "entry in ORCID to go edit. They'll be picked up automatically the next",
        "time the graph is rebuilt.",
        "",
    ]
    for (name, orcid), items in sorted(by_person.items()):
        lines.append(f"## {name} ({orcid})")
        lines.append("")
        lines.extend(_issue_lines(items))
        lines.append("")

    Path(path).write_text("\n".join(lines))


def write_person_reports(report, reports_dir):
    """One paste-able snippet per colleague (for emailing/messaging them
    directly), alongside the combined report from write_report(). Stale
    snippets for colleagues who no longer have any open issues are removed."""
    reports_dir = Path(reports_dir)
    by_person = _group_by_person(report)

    existing = set(reports_dir.glob("*.md")) if reports_dir.exists() else set()
    written = set()

    for (name, orcid), items in by_person.items():
        if not orcid:
            continue
        reports_dir.mkdir(parents=True, exist_ok=True)
        orcid_id = orcid.rsplit("/", 1)[-1]
        family_name = items[0].get("person_family_name")
        stem = f"{_slugify(family_name)}-{orcid_id}" if family_name else orcid_id
        path = reports_dir / f"{stem}.md"
        lines = [
            f"Hi — a couple of things in your ORCID record ({orcid}) would help this",
            "colleague graph link up cleanly if you have a moment to fix them:",
            "",
        ]
        lines.extend(_issue_lines(items))
        path.write_text("\n".join(lines) + "\n")
        written.add(path)

    for stale in existing - written:
        stale.unlink()
